### ISSUE TITLE
Using MKFoundationKit for OS X with CocoaPods

### ISSUE THREAD

**Issue by edasque** [michalkonturek/MKFoundationKit#3]
Similarly to https://github.com/michalkonturek/MKUnits/issues/7 if I try to use MKFoundationKit in an OS X application:
`...is not compatible with `MKFoundationKit/NSNumber (1.2.3)`, which does not support `OS X`

**Comment by michalkonturek** [comment]
MKFoundationKit was written for iOS only - the pod spec specifies only iOS as deployment platform https://github.com/michalkonturek/MKFoundationKit/blob/master/MKFoundationKit.podspec

I don't do OS X apps at the moment, butI guess I will make a deployment target for both iOS and OS X one day.

**Comment by edasque** [comment]
It works fine with OS X once you change the target, FYI

**Comment by michalkonturek** [comment]
Cheers. It's on my backlog, so I guess I should make changes within a month ;)
